services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - network-app

  app:
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile
    image: my-select-shop
    container_name: my-select-shop
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/mydb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - mysql
    networks:
      - network-app

volumes:
  db:

networks:
  network-app:
    driver: bridge
